Ccj
gunaworks/crowci pull request #3
Opened 2024-04-16 20:38 UTC by charucjoshi

Removed redundant code and files.

2024-04-17 07:28 UTC, sharath2106 requested changes
Have asked for some changes which is more about structuring the implementation for better maintainability and readability.

2024-04-18 07:15 UTC, sharath2106 commented on github_push.py
> +def push(access_token, yaml_content, repository_link):
I would keep it push_to_github because yaml is already a parameter.

2024-04-18 08:09 UTC, charucjoshi commented on github_push.py
> +def push(access_token, yaml_content, repository_link):
ok... changed the method name to push_to_github which was previously the name of the push to github button. Button's name changed to push_to_github_button.

2024-04-18 10:50 UTC, sharath2106 commented
Looks good to me.

2024-04-18 11:47 UTC, merged